# Generated by Django 3.0.5 on 2020-04-24 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pitanja.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=100)),
                ('mesto', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'škola',
                'verbose_name_plural': 'škole',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('datum_formiranja', models.DateField(default=pitanja.models.sada)),
                ('datum_vazenja', models.DateField(default=pitanja.models.sutra)),
            ],
            options={
                'verbose_name': 'test',
                'verbose_name_plural': 'testovi',
            },
        ),
        migrations.CreateModel(
            name='Ucenik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Skola')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'učenik',
                'verbose_name_plural': 'učenici',
            },
        ),
        migrations.CreateModel(
            name='TestUcenika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocetak_rada', models.DateTimeField(default=pitanja.models.sada)),
                ('kraj_rada', models.DateTimeField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Test')),
                ('ucenik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Ucenik', verbose_name='učenik')),
            ],
            options={
                'verbose_name': 'test učenika',
                'verbose_name_plural': 'testovi učenika',
            },
        ),
        migrations.CreateModel(
            name='Pitanje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField()),
                ('tip', models.CharField(choices=[('1', 'Jedan tačan odgovor'), ('2', 'Više tačnih odgovora')], max_length=1)),
                ('tekst', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Test')),
            ],
            options={
                'verbose_name': 'pitanje',
                'verbose_name_plural': 'pitanja',
            },
        ),
        migrations.CreateModel(
            name='OdgovorUcenika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=pitanja.models.sada)),
                ('odgovor', models.CharField(max_length=100)),
                ('pitanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje')),
                ('test_ucenika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.TestUcenika', verbose_name='test učenika')),
            ],
            options={
                'verbose_name': 'odgovor učenika',
                'verbose_name_plural': 'odgovori učenika',
            },
        ),
        migrations.CreateModel(
            name='Odgovor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redni_broj', models.PositiveSmallIntegerField()),
                ('tekst', models.TextField()),
                ('tacan', models.BooleanField()),
                ('pitanje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje')),
            ],
            options={
                'verbose_name': 'odgovor',
                'verbose_name_plural': 'odgovori',
            },
        ),
    ]
